### ISSUE TITLE
Add metrics for grok parse failures

### ISSUE THREAD

**Issue by runningman84** [logstash-plugins/logstash-filter-grok#104]
These are the current metrics:
```
{
        "id" : "syslog_grok_1",
        "events" : {
          "duration_in_millis" : 101,
          "in" : 103,
          "out" : 103
        },
        "matches" : 103,
        "patterns_per_field" : {
          "message" : 1
        }
```
Please add the number of grok parse failures?

https://github.com/elastic/logstash/issues/6405#issuecomment-267383156

**Comment by jsvd** [comment]
added in https://github.com/logstash-plugins/logstash-filter-grok/pull/85 (see [here](https://github.com/logstash-plugins/logstash-filter-grok/pull/85/files#diff-0d9c333ff736a82e8686ba9c4bb5e919R279))
