### ISSUE TITLE
Grok 3.4.5 (not released yet) is not BwC with LS 5.5.x

### ISSUE THREAD

**Issue by original-brownbear** [logstash-plugins/logstash-filter-grok#129]
#125 introduced the use of the cached counters for metrics, only available in `5.6.x` => once we release `3.4.5` it won't be compatible with LS `5.5.x`.

I like @jsvd 's suggestion to branch of `3.x` (without this change) and bump the version here major version in `master` (+ require LS `>= 5.6` in `master`).

cc @jsvd , @andrewvc

**Comment by jsvd** [comment]
This has been done, [branch 3.x now exists](https://github.com/logstash-plugins/logstash-filter-grok/tree/3.x) and [version 4.0.0 has been released with a dependency on logstash-core >= 5.6.0](https://rubygems.org/gems/logstash-filter-grok/versions/4.0.0)
