### ISSUE TITLE
Plugin breaks configtest

### ISSUE THREAD

**Issue by hinnerk** [logstash-plugins/logstash-filter-grok#14]
With the current beta this happens on configtest:

    grok must set a milestone. For more information about plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones

Since the `geoip` plugin breaks too apparently `logstash plugin update` is currently not to be used, right?

**Comment by untergeek** [comment]
Sorry for the pain and confusion.  Milestones are deprecated in the 1.5 master branch and are going away.  You can temporarily address this for Beta1 by simply adding `milestone 3` above the top `config` declaration.
