### ISSUE TITLE
Maybe support date parsing?

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-grok#19]
Often users are confused that matching a timestamp text doesn't actually inform logstash as to the correct time the event occurred.

Maybe something like `%{MYTIMEPATTERN:+time_format}` would imply capturing the text and parsing it with time_format and setting @timestamp? 

Anyone have thoughts?

**Comment by untergeek** [comment]
I do think it's too complex.  Have one filter do one thing at a time, generally speaking, and have it do it well.

Just because a thing _can_ be done does not imply that it should, or must be done.

Simplicity often means saying, "No," to a lot of things.

**Comment by jordansissel** [comment]
I was noodling on the possible benefits. Doing this would let you embed the time format within your pattern, so SYSLOGBASE could have a defined timestamp pattern within it, and you could match:

```
  match => { "message" => "%{SYSLOGBASE} whatever" } 
```

and you get `@timestamp` set implicitly if SYSLOGBASE has a pattern within it that uses the proposed time parsing.

**Comment by jordansissel** [comment]
This would simplify tutorials ("%{COMBINEDAPACHELOG}" grok only, no date filter) etc

**Comment by jordansissel** [comment]
On the other hand, I like one filter doing one thing each.

But, the contrary, grok already parses text and does int/float conversion, why not time?

**Comment by untergeek** [comment]
That idea does have merit, for pre-defined time formats.  And if you can define those, the language to make it possible for others also makes sense.  

Will this functionality depend on the presence of the date filter as well, then?  If so, will it be JRuby-only, as the date filter depends on Joda?

**Comment by untergeek** [comment]
The pipelining of filters makes a lot of sense to me.  Trying to make one stage do too much can bog things down, and also make it harder to pin down "which filter is the bottleneck."

**Comment by jordansissel** [comment]
A counterpoint to "why not time?" I can think of is that it's unclear when the road ends there. "why not geoip?" etc.

I think my intent from this discussion is to find the reasons why time parsing would be nice, and try to generalize that and provide a good solution that, my gut says, won't involve grok feature changes. We have, for example, needs to provide a kind of 'parser pack' for known kinsd of logs (apache == grok + date + geoip + useragent) that would be useful to have solved.

**Comment by jordansissel** [comment]
This discussion was useful, but I Don't think we've decided what to do, and we haven't discussed it in a while. Will close.

We can always revisit this topic later :)
