### ISSUE TITLE
Grok tag_on_failure not deprecated

### ISSUE THREAD

**Issue by pemontto** [logstash-plugins/logstash-filter-grok#56]
I was reading the docs and noticed that [tag_on_failure](https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-tag_on_failure) is not marked deprecated even though tags are. Is this likely to be updated or replaced by writing to a user defined field?

**Comment by wiibaa** [comment]
@pemontto there is a misundertanding, the usage of tags in an event is not deprecated at all. so the tag_on_faiulre is still valid to use. What is deprecated is *event filtering with filter parameters* like **tags**.  Using conditionals statement around the filter like `if "failure" in [tags]`  is the way to go.

**Comment by pemontto** [comment]
Thanks for the clarification wilbaa
