### ISSUE TITLE
filter inclusion "in" operator doesn't work with one element

### ISSUE THREAD

**Issue by sebbarg** [logstash-plugins/logstash-filter-grok#74]
Hi,

Running Logstash 2.2.1.

It looks like there is a problem with the "in" operator when the array being searched only contains one element. In the below example field "foo1" isn't added:

```
if ( "foo" in ["foo"] ) {                               
  mutate { add_field => ["foo1", "nope"] }              
}  
```                                                     

Here it works (field "foo2" is correctly added):
                                                        
```
if ( "foo" in ["foo", "bar"] )  {                       
  mutate { add_field => ["foo2", "yep"] }               
}      
```                                                 

Am I missing something?

**Comment by wiibaa** [comment]
Hello,
as this is not a grok specific issue, could you please close this in favor of upvoting https://github.com/elastic/logstash/issues/2129.

Thanks
