### ISSUE TITLE
unable to install the logstash-filter-grok plugin

### ISSUE THREAD

**Issue by superhobbit** [logstash-plugins/logstash-filter-grok#83]
I followed the installation steps but when I install the plugin it shows this error:
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core-plugin-api":
In snapshot (Gemfile.lock):
logstash-core-plugin-api (= 1.10.0)

In Gemfile:
logstash-filter-geoip (>= 0) java depends on
logstash-core-plugin-api (~> 1.0) java

logstash-filter-geoip (>= 0) java depends on
  logstash-core-plugin-api (~> 1.0) java

logstash-filter-geoip (>= 0) java depends on
  logstash-core-plugin-api (~> 1.0) java

Running bundle update will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

I could really use some help...Thanks a lot!!

**Comment by jordansissel** [comment]
Can you show what you ran that gave you this error?

**Comment by superhobbit** [comment]
Thanks for your reply!I ran: bin/logstash-plugin install logstash-filter-grok.
Yet..I ask the question in the http://discuss.elastic.co.They said the plugin is included as part of the core LS release so there is no need to install it manually..So my problem has been solved,but I suppose maybe it's better to note this in the installation guide?In case someone else would met the same error
